---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:master
        name: grafana
        resources: {}
        ports:
        - name: grafana
          containerPort: 3000
          protocol: TCP
status: {}