apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-01-07T23:16:01Z"
  labels:
    app: grafana
  name: grafana-svc
  namespace: grafana
spec:
  ports:
  - nodePort: 30000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: NodePort
