---
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: reverson/app_metrics:latest
        name: app
        resources: {}
        env:
        - name: DB_HOST
          value: db-svc.db.svc.cluster.local
        - name: DB_PASSWD
          value: testpassword
        - name: DB_USER
          value: test_user
        - name: DB_NAME
          value: dbtest