---
apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres
        name: db
        resources: {}
        ports:
          - name: db
            containerPort: 5432
            protocol: TCP
        env:
        - name: POSTGRES_PASSWORD
          value: testpassword
        - name: POSTGRES_USER
          value: test_user