---
apiVersion: v1
kind: Namespace
metadata:
  name: worker
---
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: reverson/work_metrics:latest
        name: worker
        resources: {}
        env:
        - name: INFLUXDB_HOST
          value: influxdb-svc.influxdb.svc.cluster.local
        - name: INFLUXDB_PORT
          value: 8086
        - name: REDIS_HOST
          value: redis-svc.redis.svc.cluster.local
